# Deploy chronograf + influxdb + kapacitor + mongodb
version: '3.3'
services:
  mongo:
    image: mongo:4.4.0-bionic
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - '127.0.0.1:27018:27017'
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
  influx:
    image: influxdb:1.8
    container_name: influxdb
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
      - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      #- ./influx/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - '127.0.0.1:8086:8086'
      - '127.0.0.1:8088:8088'
    restart: always
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - ./chronograf-storage:/var/lib/chronograf
    depends_on:
      - influx
    environment:
      - INFLUXDB_URL=http://influx:8086
  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influx:8086
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor
    links:
      - influx
    # ports:
    #   - "9092:9092"
